[[redirects]]
from = "/*"
to = "/index.html"
status = 200
[build]
command = "curl -sSL https://github.com/getzola/zola/releases/download/v0.19.3/zola-v0.19.3-x86_64-unknown-linux-gnu.tar.gz | tar -xz && ./zola build"
publish = "public"
