[[project]]
name = "Full-Stack Food Recipe Management App"
desc = "<ul><li>Developed a full-stack Food Recipe web app with React.js, Node.js, Express, and
MongoDB.</li><li>Implemented secure authentication, CRUD operations, and user-specific access
control.</li><li>Enabled recipe image uploads and implemented a feature to mark recipes as
favorites for quick access.</li><li>Deployed frontend on Netlify and backend on Render for seamless user
experience.</li></ul>"
tags = []
img = "../../../projects/food-recipe.png"
links = [
  { name = "Live Site", url = "https://manishfoodrecipe.netlify.app/" },
  { name = "Github", url = "https://github.com/SAIMANISH18/Food_Recipe" }
]

[[project]]
name = "Restaurant Menu"
desc = "<ul><li>Dynamic restaurant menu created using React.js.</li><li>Includes dish descriptions, prices, and categories.</li><li>Enables easy browsing of available items.</li></ul>"
tags = []
img = "../../../projects/resturent.png"
links = [
  { name = "Live Site", url = "https://manishrestaurent-menu.netlify.app/" },
  { name = "Github", url = "https://github.com/SAIMANISH18/Manish-Restaurant-Menu" }
]

[[project]]
name = "Weather forecast finder"
desc = "<ul><li>Provides real-time weather updates by city.</li><li>Displays temperature, humidity, and wind details.</li><li>Powered by a reliable weather API.</li></ul>"
tags = []
img = "../../../projects/Weather.png"
links = [
  { name = "Live Site", url = "https://weather-forecastfinder.netlify.app/" },
  { name = "Github", url = "https://github.com/SAIMANISH18/weather-app" }
]

[[project]]
name = "Text Converter Utility"
desc = "<ul><li> Built with React.js for quick text manipulation.</li><li>Offers case conversion, word count and character count options.</li><li>Designed for efficient, on-the-go text processing.</li></ul>"
tags = []
img = "../../../projects/text-converter.png"
links = [
  { name = "Live Site", url = "https://textcoverterusing-reactjs.netlify.app/" },
  { name = "Github", url = "https://github.com/SAIMANISH18/textCoverter-using-ReactJs" }
]

 